name: market_place_customer
description: "Market Place Nearby App"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  pinput: ^5.0.2
  dropdown_button2: ^2.3.9
  image_picker: ^1.2.0
  file_picker: ^10.3.3
  dotted_border: ^2.1.0
  http: ^1.5.0
  geolocator: ^13.0.2
  dio: ^5.9.0
  flutter_bloc: ^9.1.1
  flutter_easyloading: ^3.0.5
  intl: ^0.20.2
  shared_preferences: ^2.5.3
  shimmer: ^3.0.0
  url_launcher: ^6.3.2
  path_provider: ^2.1.5
  flutter_image_compress: ^2.4.0
  permission_handler: ^12.0.1
  flutter_dotenv: ^6.0.0
  firebase_messaging: ^16.0.2
  slider_button: ^2.1.0
  ticket_widget: ^1.0.2
  percent_indicator: ^4.2.5
  upgrader: ^12.1.0
  country_state_city_pro: ^0.0.6
  google_maps_flutter: ^2.12.3
  flutter_animate: ^4.5.2
  geocoding: ^4.0.0
  smooth_page_indicator: ^1.2.1
  carousel_slider: ^5.1.1
  photo_view: ^0.15.0
  draggable_carousel_slider: ^0.0.1
  razorpay_flutter: ^1.4.0
  cloud_firestore: ^6.0.3
  confetti: ^0.8.0
  animate_do: ^4.2.0
  qr_flutter: ^4.1.0
  webview_flutter: ^4.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/font/
    - .env

  fonts:
    - family: AlanSans
      fonts:
        - asset: assets/font/AlanSans-Regular.ttf
        - asset: assets/font/AlanSans-Medium.ttf
          weight: 500
        - asset: assets/font/AlanSans-SemiBold.ttf
          weight: 700

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.jpg"
